version: 1.0.{build}
image: Visual Studio 2019

configuration: Release

branches:
  only:
    - master
    - dev
    - conv
    
before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: calculator.sln
  verbosity: minimal
