image: Visual Studio 2019

before_build:
 - nuget restore
build_script:
 - msbuild /verbosity:quiet "calculator.sln"
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"CalculatorUnitTests\bin\Debug\CalculatorUnitTests.dll  -noshadow" -output:"coverage.xml" -filter:"+[Calculator*]* -[CalculatorUnitTests*]*"
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t 833e676a-d5df-4ae9-ac0b-ca5605ff79f5


branches:
  only:
    - master
    - dev

