image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: calculator.sln
  verbosity: minimal
  
branches:
  only:
    - master
    - dev
    - conv

test_script:
- OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:"".\CalculatorUnitTests\bin\Debug\MyUnitTests.dll" -filter:"+[Calculator*]* -[CalculatorUnitTests*]*" -output:".\Calculator_coverage.xml"
- codecov -f "Calculator_coverage.xml" -t 833e676a-d5df-4ae9-ac0b-ca5605ff79f5
