version: 1.0.{build}
image: Visual Studio 2017

configuration: Release

branches:
  only:
    - master
    - dev
    - conv
    
before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: calculator.sln
  verbosity: minimal

after_test:
- OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\MSTest.exe" -targetargs:"/noresults /noisolation /testcontainer:"".\CalculatorUnitTests\bin\Release\CalculatorUnitTests.dll" -output:".\Calculator_coverage.xml"
- codecov -f "Calculator_coverage.xml" -t 833e676a-d5df-4ae9-ac0b-ca5605ff79f5