image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
 project: calculator.sln
 verbosity: minimal

artifacts:
- path: calculator/bin/Debug/calculator.exe
  name: calculator

branches:
  only:
    - master
    - dev
before_build:
 - nuget restore
build_script:
 - msbuild /verbosity:quiet "calculator.sln"
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"CalculatorUnitTests\bin\Debug\CalculatorUnitTests.dll  -noshadow" -output:"coverage.xml" -filter:"+[CalculatorUnitTests*]* -[CalculatorUnitTests*]*"
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.s
